// <auto-generated />
namespace Reach.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class Remark : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Remark));
        
        string IMigrationMetadata.Id
        {
            get { return "201502030508061_Remark"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
